spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: root
    username: postgres
    url: jdbc:postgresql://localhost:5432/contact-managment
  main:
    allow-circular-references: 'true'

flyway:
    baselineOnMigrate: 'true'
    url: jdbc:postgresql://localhost:5432
    user: postgres
    password: root
    schemas: contact-managment
    locations: filesystem:db/migration



